// <auto-generated />
using System;
using Apolo.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Apolo.Infra.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200323195931_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("Apolo.Domain.Models.Songs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Apolo.Domain.Models.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SongsId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SongsId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Apolo.Domain.Models.Users", b =>
                {
                    b.HasOne("Apolo.Domain.Models.Songs", null)
                        .WithMany("LikedBy")
                        .HasForeignKey("SongsId");
                });
#pragma warning restore 612, 618
        }
    }
}
